print ("HelloWorldHI")
print ("Jmeter studying!!!")
print ("sakib!")
print ("Tanvir")
print ("changed by Sakib1")
print ("Updated from my Home--This is Sakib")
print ("world.")
print ("Finally with some trouble...in git config from terminal managed to crack it! ")